include: package:lint/analysis_options.yaml

analyzer:
  errors:
    # allow having TODOs in the code
    todo: ignore


linter:
  rules:
    # Use parameter order as in json response
    always_put_required_named_parameters_first: false
    
    # Util classes are awesome!
    avoid_classes_with_only_static_members: false

    # Make constructors the first thing in every class
    sort_constructors_first: true

    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: false
