name: kana_plus_plus
description: An app which gives the oportunity to training hiragana and katakana using writing and avoiding the mother language to learn new words.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  scroll_to_index: ^2.0.0
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
  uses-material-design: true
  
  assets:
    - lib/assets/icons/black/about.png
    - lib/assets/icons/black/dark_mode.png
    - lib/assets/icons/black/eraser.png
    - lib/assets/icons/black/hiragana_katakana.png
    - lib/assets/icons/black/hiragana.png
    - lib/assets/icons/black/katakana.png
    - lib/assets/icons/black/language.png
    - lib/assets/icons/black/light_mode.png
    - lib/assets/icons/black/privacy_policy.png
    - lib/assets/icons/black/quantity_of_words.png
    - lib/assets/icons/black/quit.png
    - lib/assets/icons/black/show_hint.png
    - lib/assets/icons/black/support.png
    - lib/assets/icons/black/undo.png
    - lib/assets/icons/black/writing_hand_left.png
    - lib/assets/icons/black/writing_hand_right.png

    - lib/assets/images/words/rain.png
    - lib/assets/images/kanas/h_a.png
    - lib/assets/images/kanas/r_a.png

    - lib/assets/images/square.png
    - lib/assets/images/correct.png
    - lib/assets/images/wrong.png
    - lib/assets/images/h_a_test.png
