name: kana_plus_plus
description: An app which gives the oportunity to training hiragana and katakana using writing and avoiding the mother language to learn new words.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.2
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  logger: ^1.0.0
  path: ^1.8.0
  path_provider: ^2.0.2
  provider: ^5.0.0
  scroll_to_index: ^2.0.0
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+4
  step_progress_indicator: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  mocktail: ^0.1.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - lib/assets/database/

    - lib/assets/icons/

    - lib/assets/tests/images/
    - lib/assets/tests/images/banners/
    - lib/assets/tests/images/kanas/
    - lib/assets/tests/images/words/

    - lib/assets/images/
    - lib/assets/images/banners/
    - lib/assets/images/kanas/
    - lib/assets/images/menu/kanas/
    - lib/assets/images/words/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: lib/assets/fonts/permanent_marker/PermanentMarker-Regular.ttf
