name: kwriting
description: KWriting

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.1+3

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  bloc: ^7.2.1
  carousel_slider: ^4.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_device_type: ^0.4.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.23.0+1
  google_mobile_ads: ^1.0.0
  hive: ^2.0.4
  in_app_review: ^2.0.3
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  launch_review: ^3.0.1
  package_info_plus: ^1.3.0
  path_provider: ^2.0.7
  provider: ^6.0.0
  share_plus: ^3.0.2
  step_progress_indicator: ^1.0.1
  url_launcher: ^6.0.11

dev_dependencies:
  bloc_test: ^8.5.0
  build_runner: ^2.1.4
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  mocktail: ^0.2.0

flutter_icons:
  android: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "assets/icons/app_icon_background.png"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/database/

    - assets/icons/

    - assets/images/
    - assets/images/banners/
    - assets/images/kanas/
    - assets/images/menu/kanas/
    - assets/images/menu/introduction/
    - assets/images/words/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/fonts/permanent_marker/PermanentMarker-Regular.ttf
    - family: PT Sans
      fonts:
        - asset: assets/fonts/pt_sans/PTSans-Regular.ttf
        - asset: assets/fonts/pt_sans/PTSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/pt_sans/PTSans-Italic.ttf
          style: italic
        - asset: assets/fonts/pt_sans/PTSans-BoldItalic.ttf
          style: italic
          weight: 700
    - family: M PLUS Rounded 1c
      fonts:
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-Thin.ttf
          weight: 100
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-Light.ttf
          weight: 300
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-Regular.ttf
          weight: 400
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-Medium.ttf
          weight: 500
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-Bold.ttf
          weight: 700
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/m_plus_rounded_1c/MPLUSRounded1c-Black.ttf
          weight: 900