name: kana_plus_plus
description: An app which gives the oportunity to training hiragana and katakana using writing and avoiding the mother language to learn new words.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.2
  google_fonts: ^2.1.0
  intl: ^0.17.0
  path:
  path_provider: ^2.0.2
  provider: ^5.0.0
  scroll_to_index: ^2.0.0
  shared_preferences: ^2.0.6
  sqflite:

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - lib/assets/icons/black/about.png
    - lib/assets/icons/black/dark_theme.png
    - lib/assets/icons/black/eraser.png
    - lib/assets/icons/black/hiragana_katakana.png
    - lib/assets/icons/black/hiragana.png
    - lib/assets/icons/black/katakana.png
    - lib/assets/icons/black/language.png
    - lib/assets/icons/black/light_theme.png
    - lib/assets/icons/black/privacy_policy.png
    - lib/assets/icons/black/quantity_of_words.png
    - lib/assets/icons/black/quit.png
    - lib/assets/icons/black/show_hint.png
    - lib/assets/icons/black/not_show_hint.png
    - lib/assets/icons/black/support.png
    - lib/assets/icons/black/undo.png
    - lib/assets/icons/black/writing_hand_left.png
    - lib/assets/icons/black/writing_hand_right.png

    - lib/assets/images/kanas/h_a.png
    - lib/assets/images/kanas/r_a.png

    - lib/assets/images/square.png
    - lib/assets/images/correct.png
    - lib/assets/images/wrong.png
    - lib/assets/images/h_a_test.png

    - lib/assets/images/words/cat.png
    - lib/assets/images/words/dog.png
    - lib/assets/images/words/bird.png
    - lib/assets/images/words/rabbit.png
    - lib/assets/images/words/cow.png
    - lib/assets/images/words/horse.png
    - lib/assets/images/words/sheep.png
    - lib/assets/images/words/goat.png
    - lib/assets/images/words/pig.png
    - lib/assets/images/words/insect.png
    - lib/assets/images/words/bee.png
    - lib/assets/images/words/spider.png
    - lib/assets/images/words/ant.png
    - lib/assets/images/words/fish.png
    - lib/assets/images/words/turtle.png
    - lib/assets/images/words/snake.png
    - lib/assets/images/words/crocodile.png
    - lib/assets/images/words/shrimp.png
    - lib/assets/images/words/frog.png
    - lib/assets/images/words/sun.png
    - lib/assets/images/words/moon.png
    - lib/assets/images/words/mountain.png
    - lib/assets/images/words/cave.png
    - lib/assets/images/words/island.png
    - lib/assets/images/words/sea.png
    - lib/assets/images/words/river.png
    - lib/assets/images/words/pond.png
    - lib/assets/images/words/waterfall.png
    - lib/assets/images/words/tree.png
    - lib/assets/images/words/forest.png
    - lib/assets/images/words/flower.png
    - lib/assets/images/words/spring.png
    - lib/assets/images/words/summer.png
    - lib/assets/images/words/fall.png
    - lib/assets/images/words/winter.png
    - lib/assets/images/words/snow.png
    - lib/assets/images/words/rain.png
    - lib/assets/images/words/storm.png
    - lib/assets/images/words/rainbow.png
    - lib/assets/images/words/box_lunch.png
    - lib/assets/images/words/raw_fish.png
    - lib/assets/images/words/sushi.png
    - lib/assets/images/words/miso_soup.png
    - lib/assets/images/words/ramen.png
    - lib/assets/images/words/meat.png
    - lib/assets/images/words/sausage.png
    - lib/assets/images/words/egg.png
    - lib/assets/images/words/honey.png
    - lib/assets/images/words/carrot.png
    - lib/assets/images/words/garlic.png
    - lib/assets/images/words/lettuce.png
    - lib/assets/images/words/broccoli.png
    - lib/assets/images/words/cauliflower.png
    - lib/assets/images/words/tomato.png
    - lib/assets/images/words/potato.png
    - lib/assets/images/words/eggplant.png
    - lib/assets/images/words/mushroom.png
    - lib/assets/images/words/pumpkin.png
    - lib/assets/images/words/peanut.png
    - lib/assets/images/words/apple.png
    - lib/assets/images/words/orange.png
    - lib/assets/images/words/banana.png
    - lib/assets/images/words/watermelon.png
    - lib/assets/images/words/strawberry.png
    - lib/assets/images/words/pineapple.png
    - lib/assets/images/words/grape.png
    - lib/assets/images/words/cherry.png
    - lib/assets/images/words/melon.png
    - lib/assets/images/words/coconut.png
    - lib/assets/images/words/avocado.png
    - lib/assets/images/words/water.png
    - lib/assets/images/words/coffee.png
    - lib/assets/images/words/tea.png
    - lib/assets/images/words/milk.png
    - lib/assets/images/words/alcoholic_drink.png
    - lib/assets/images/words/wine.png
    - lib/assets/images/words/beer.png
    - lib/assets/images/words/car.png
    - lib/assets/images/words/taxi.png
    - lib/assets/images/words/bus.png
    - lib/assets/images/words/truck.png
    - lib/assets/images/words/motorcycle.png
    - lib/assets/images/words/bicycle.png
    - lib/assets/images/words/train.png
    - lib/assets/images/words/subway.png
    - lib/assets/images/words/ship.png
    - lib/assets/images/words/boat.png
    - lib/assets/images/words/airplane.png
    - lib/assets/images/words/helicopter.png
    - lib/assets/images/words/rocket.png
    - lib/assets/images/words/train_station.png
    - lib/assets/images/words/airport.png
    - lib/assets/images/words/harbour.png
    - lib/assets/images/words/bank.png
    - lib/assets/images/words/hospital.png
    - lib/assets/images/words/school.png
    - lib/assets/images/words/library.png
    - lib/assets/images/words/hotel.png
    - lib/assets/images/words/factory.png
    - lib/assets/images/words/church.png
    - lib/assets/images/words/zoo.png
    - lib/assets/images/words/shop.png
    - lib/assets/images/words/pharmacy.png
    - lib/assets/images/words/bar.png
    - lib/assets/images/words/department_store.png
    - lib/assets/images/words/supermarket.png
    - lib/assets/images/words/coffee_shop.png
    - lib/assets/images/words/restaurant.png
    - lib/assets/images/words/notebook.png
    - lib/assets/images/words/pencil.png
    - lib/assets/images/words/eraser.png
    - lib/assets/images/words/pen.png
    - lib/assets/images/words/book.png
    - lib/assets/images/words/desk.png
    - lib/assets/images/words/paper.png
    - lib/assets/images/words/scissors.png
    - lib/assets/images/words/computer.png
    - lib/assets/images/words/cellphone.png
    - lib/assets/images/words/telephone.png
    - lib/assets/images/words/atm.png
    - lib/assets/images/words/house.png
    - lib/assets/images/words/bedroom.png
    - lib/assets/images/words/kitchen.png
    - lib/assets/images/words/toilet.png
    - lib/assets/images/words/door.png
    - lib/assets/images/words/key.png
    - lib/assets/images/words/window.png
    - lib/assets/images/words/wardrobe.png
    - lib/assets/images/words/chair.png
    - lib/assets/images/words/sofa.png
    - lib/assets/images/words/bed.png
    - lib/assets/images/words/refrigerator.png
    - lib/assets/images/words/washing_machine.png
    - lib/assets/images/words/television.png
    - lib/assets/images/words/iron.png
    - lib/assets/images/words/air-conditioner.png
    - lib/assets/images/words/electric_fan.png
    - lib/assets/images/words/microwave_oven.png
    - lib/assets/images/words/stove.png
    - lib/assets/images/words/chopsticks.png
    - lib/assets/images/words/glass.png
    - lib/assets/images/words/spoon.png
    - lib/assets/images/words/fork.png
    - lib/assets/images/words/dining_room.png
    - lib/assets/images/words/towel.png
    - lib/assets/images/words/shower.png
    - lib/assets/images/words/soap.png
    - lib/assets/images/words/shampoo.png
    - lib/assets/images/words/toothpaste.png
    - lib/assets/images/words/t-shirt.png
    - lib/assets/images/words/coat.png
    - lib/assets/images/words/raincoat.png
    - lib/assets/images/words/underwear.png
    - lib/assets/images/words/jacket.png
    - lib/assets/images/words/dress.png
    - lib/assets/images/words/shorts.png
    - lib/assets/images/words/jeans.png
    - lib/assets/images/words/earring.png
    - lib/assets/images/words/necklace.png
    - lib/assets/images/words/belt.png
    - lib/assets/images/words/slippers.png
    - lib/assets/images/words/sandals.png
    - lib/assets/images/words/boots.png
    - lib/assets/images/words/America.png
    - lib/assets/images/words/Argentina.png
    - lib/assets/images/words/Australia.png
    - lib/assets/images/words/Brazil.png
    - lib/assets/images/words/Chile.png
    - lib/assets/images/words/Egypt.png
    - lib/assets/images/words/France.png
    - lib/assets/images/words/Germany.png
    - lib/assets/images/words/United_Kingdom.png
    - lib/assets/images/words/Italy.png
    - lib/assets/images/words/Japan.png
    - lib/assets/images/words/Mexico.png
    - lib/assets/images/words/Morocco.png
    - lib/assets/images/words/New_Zealand.png
    - lib/assets/images/words/Nigeria.png
    - lib/assets/images/words/Philippines.png
    - lib/assets/images/words/Portugal.png
    - lib/assets/images/words/Russia.png
    - lib/assets/images/words/South_Africa.png
    - lib/assets/images/words/South_Korea.png
    - lib/assets/images/words/Spain.png
    - lib/assets/images/words/Thailand.png
    - lib/assets/images/words/Turkey.png
    - lib/assets/images/words/baseball.png
    - lib/assets/images/words/swimming.png
    - lib/assets/images/words/table_tennis.png
    - lib/assets/images/words/soccer.png
    - lib/assets/images/words/tennis.png
    - lib/assets/images/words/basketball.png
    - lib/assets/images/words/volleyball.png
    - lib/assets/images/words/football.png
    - lib/assets/images/words/rugby.png
    - lib/assets/images/words/boxing.png
    - lib/assets/images/words/white.png
    - lib/assets/images/words/black.png
    - lib/assets/images/words/red.png
    - lib/assets/images/words/blue.png
    - lib/assets/images/words/green.png
    - lib/assets/images/words/yellow.png
    - lib/assets/images/words/brown.png
    - lib/assets/images/words/gold.png
    - lib/assets/images/words/silver.png
    - lib/assets/images/words/pink.png
    - lib/assets/images/words/orange_c.png
    - lib/assets/images/words/ice_cream.png
    - lib/assets/images/words/butter.png
    - lib/assets/images/words/button.png
    - lib/assets/images/words/ticket.png
    - lib/assets/images/words/bread.png
    - lib/assets/images/words/pizza.png
    - lib/assets/images/words/potato_chips.png
    - lib/assets/images/words/sandwich.png
    - lib/assets/images/words/salad.png
