name: stroke_reducer
description: Reduce the quantity of points of a stroke.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  flutter_lints: ^1.0.4
  mocktail: ^0.2.0
  test: ^1.19.2
