name: stroke_reducer
description: Reduce the quantity of points of a stroke.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  mocktail: ^0.2.0
  test: ^1.19.3

flutter:
  uses-material-design: true